root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./cmd/server/main.go"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test.go"]
delay = 1000
stop_old = true
log = "air.log"

[log]
time = true