package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphql1 "github.com/gitwb-c/crm.saas/backend/internal/graphql"
	"github.com/gitwb-c/crm.saas/backend/internal/wire"
)

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, input graphql1.LoginInput) (*graphql1.NewLogin, error) {
	service := wire.InitializeEmployeeAuthService(r.Client)
	login, err := service.ValidateLogin(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return (*graphql1.NewLogin)(&login), err
}
