// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/crmfield"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/deal"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/dealcrmfield"
	"github.com/google/uuid"
)

// DealCrmFieldCreate is the builder for creating a DealCrmField entity.
type DealCrmFieldCreate struct {
	config
	mutation *DealCrmFieldMutation
	hooks    []Hook
}

// SetValue sets the "value" field.
func (_c *DealCrmFieldCreate) SetValue(v string) *DealCrmFieldCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *DealCrmFieldCreate) SetCreatedAt(v time.Time) *DealCrmFieldCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *DealCrmFieldCreate) SetNillableCreatedAt(v *time.Time) *DealCrmFieldCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *DealCrmFieldCreate) SetUpdatedAt(v time.Time) *DealCrmFieldCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *DealCrmFieldCreate) SetNillableUpdatedAt(v *time.Time) *DealCrmFieldCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DealCrmFieldCreate) SetID(v uuid.UUID) *DealCrmFieldCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DealCrmFieldCreate) SetNillableID(v *uuid.UUID) *DealCrmFieldCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDealID sets the "deal" edge to the Deal entity by ID.
func (_c *DealCrmFieldCreate) SetDealID(id uuid.UUID) *DealCrmFieldCreate {
	_c.mutation.SetDealID(id)
	return _c
}

// SetDeal sets the "deal" edge to the Deal entity.
func (_c *DealCrmFieldCreate) SetDeal(v *Deal) *DealCrmFieldCreate {
	return _c.SetDealID(v.ID)
}

// SetCrmFieldID sets the "crmField" edge to the CrmField entity by ID.
func (_c *DealCrmFieldCreate) SetCrmFieldID(id uuid.UUID) *DealCrmFieldCreate {
	_c.mutation.SetCrmFieldID(id)
	return _c
}

// SetCrmField sets the "crmField" edge to the CrmField entity.
func (_c *DealCrmFieldCreate) SetCrmField(v *CrmField) *DealCrmFieldCreate {
	return _c.SetCrmFieldID(v.ID)
}

// Mutation returns the DealCrmFieldMutation object of the builder.
func (_c *DealCrmFieldCreate) Mutation() *DealCrmFieldMutation {
	return _c.mutation
}

// Save creates the DealCrmField in the database.
func (_c *DealCrmFieldCreate) Save(ctx context.Context) (*DealCrmField, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DealCrmFieldCreate) SaveX(ctx context.Context) *DealCrmField {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DealCrmFieldCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DealCrmFieldCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DealCrmFieldCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dealcrmfield.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dealcrmfield.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dealcrmfield.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DealCrmFieldCreate) check() error {
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "DealCrmField.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := dealcrmfield.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DealCrmField.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "DealCrmField.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "DealCrmField.updatedAt"`)}
	}
	if len(_c.mutation.DealIDs()) == 0 {
		return &ValidationError{Name: "deal", err: errors.New(`ent: missing required edge "DealCrmField.deal"`)}
	}
	if len(_c.mutation.CrmFieldIDs()) == 0 {
		return &ValidationError{Name: "crmField", err: errors.New(`ent: missing required edge "DealCrmField.crmField"`)}
	}
	return nil
}

func (_c *DealCrmFieldCreate) sqlSave(ctx context.Context) (*DealCrmField, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DealCrmFieldCreate) createSpec() (*DealCrmField, *sqlgraph.CreateSpec) {
	var (
		_node = &DealCrmField{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dealcrmfield.Table, sqlgraph.NewFieldSpec(dealcrmfield.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(dealcrmfield.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dealcrmfield.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dealcrmfield.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.DealIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dealcrmfield.DealTable,
			Columns: []string{dealcrmfield.DealColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deal_crm_field_deal = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CrmFieldIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dealcrmfield.CrmFieldTable,
			Columns: []string{dealcrmfield.CrmFieldColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(crmfield.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deal_crm_field_crm_field = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DealCrmFieldCreateBulk is the builder for creating many DealCrmField entities in bulk.
type DealCrmFieldCreateBulk struct {
	config
	err      error
	builders []*DealCrmFieldCreate
}

// Save creates the DealCrmField entities in the database.
func (_c *DealCrmFieldCreateBulk) Save(ctx context.Context) ([]*DealCrmField, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DealCrmField, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DealCrmFieldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DealCrmFieldCreateBulk) SaveX(ctx context.Context) []*DealCrmField {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DealCrmFieldCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DealCrmFieldCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
