// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/company"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/employee"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/employeeauth"
	"github.com/google/uuid"
)

// EmployeeAuthCreate is the builder for creating a EmployeeAuth entity.
type EmployeeAuthCreate struct {
	config
	mutation *EmployeeAuthMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *EmployeeAuthCreate) SetName(v string) *EmployeeAuthCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *EmployeeAuthCreate) SetEmail(v string) *EmployeeAuthCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *EmployeeAuthCreate) SetPassword(v string) *EmployeeAuthCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *EmployeeAuthCreate) SetCreatedAt(v time.Time) *EmployeeAuthCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *EmployeeAuthCreate) SetNillableCreatedAt(v *time.Time) *EmployeeAuthCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *EmployeeAuthCreate) SetUpdatedAt(v time.Time) *EmployeeAuthCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *EmployeeAuthCreate) SetNillableUpdatedAt(v *time.Time) *EmployeeAuthCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantId sets the "tenantId" field.
func (_c *EmployeeAuthCreate) SetTenantId(v uuid.UUID) *EmployeeAuthCreate {
	_c.mutation.SetTenantId(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EmployeeAuthCreate) SetID(v uuid.UUID) *EmployeeAuthCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EmployeeAuthCreate) SetNillableID(v *uuid.UUID) *EmployeeAuthCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEmployeeID sets the "employee" edge to the Employee entity by ID.
func (_c *EmployeeAuthCreate) SetEmployeeID(id uuid.UUID) *EmployeeAuthCreate {
	_c.mutation.SetEmployeeID(id)
	return _c
}

// SetNillableEmployeeID sets the "employee" edge to the Employee entity by ID if the given value is not nil.
func (_c *EmployeeAuthCreate) SetNillableEmployeeID(id *uuid.UUID) *EmployeeAuthCreate {
	if id != nil {
		_c = _c.SetEmployeeID(*id)
	}
	return _c
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *EmployeeAuthCreate) SetEmployee(v *Employee) *EmployeeAuthCreate {
	return _c.SetEmployeeID(v.ID)
}

// SetTenantID sets the "tenant" edge to the Company entity by ID.
func (_c *EmployeeAuthCreate) SetTenantID(id uuid.UUID) *EmployeeAuthCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetTenant sets the "tenant" edge to the Company entity.
func (_c *EmployeeAuthCreate) SetTenant(v *Company) *EmployeeAuthCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the EmployeeAuthMutation object of the builder.
func (_c *EmployeeAuthCreate) Mutation() *EmployeeAuthMutation {
	return _c.mutation
}

// Save creates the EmployeeAuth in the database.
func (_c *EmployeeAuthCreate) Save(ctx context.Context) (*EmployeeAuth, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmployeeAuthCreate) SaveX(ctx context.Context) *EmployeeAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmployeeAuthCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmployeeAuthCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmployeeAuthCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := employeeauth.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := employeeauth.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := employeeauth.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmployeeAuthCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EmployeeAuth.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := employeeauth.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmployeeAuth.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "EmployeeAuth.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := employeeauth.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmployeeAuth.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "EmployeeAuth.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := employeeauth.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "EmployeeAuth.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "EmployeeAuth.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "EmployeeAuth.updatedAt"`)}
	}
	if _, ok := _c.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenantId", err: errors.New(`ent: missing required field "EmployeeAuth.tenantId"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "EmployeeAuth.tenant"`)}
	}
	return nil
}

func (_c *EmployeeAuthCreate) sqlSave(ctx context.Context) (*EmployeeAuth, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmployeeAuthCreate) createSpec() (*EmployeeAuth, *sqlgraph.CreateSpec) {
	var (
		_node = &EmployeeAuth{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(employeeauth.Table, sqlgraph.NewFieldSpec(employeeauth.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(employeeauth.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(employeeauth.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(employeeauth.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(employeeauth.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(employeeauth.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   employeeauth.EmployeeTable,
			Columns: []string{employeeauth.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.employee_employee_auth = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employeeauth.TenantTable,
			Columns: []string{employeeauth.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmployeeAuthCreateBulk is the builder for creating many EmployeeAuth entities in bulk.
type EmployeeAuthCreateBulk struct {
	config
	err      error
	builders []*EmployeeAuthCreate
}

// Save creates the EmployeeAuth entities in the database.
func (_c *EmployeeAuthCreateBulk) Save(ctx context.Context) ([]*EmployeeAuth, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmployeeAuth, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmployeeAuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmployeeAuthCreateBulk) SaveX(ctx context.Context) []*EmployeeAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmployeeAuthCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmployeeAuthCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
