// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"crm.saas/backend/internal/ent/employeeauth"
	"crm.saas/backend/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmployeeAuthUpdate is the builder for updating EmployeeAuth entities.
type EmployeeAuthUpdate struct {
	config
	hooks    []Hook
	mutation *EmployeeAuthMutation
}

// Where appends a list predicates to the EmployeeAuthUpdate builder.
func (_u *EmployeeAuthUpdate) Where(ps ...predicate.EmployeeAuth) *EmployeeAuthUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the EmployeeAuthMutation object of the builder.
func (_u *EmployeeAuthUpdate) Mutation() *EmployeeAuthMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmployeeAuthUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeAuthUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmployeeAuthUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeAuthUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmployeeAuthUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(employeeauth.Table, employeeauth.Columns, sqlgraph.NewFieldSpec(employeeauth.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employeeauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmployeeAuthUpdateOne is the builder for updating a single EmployeeAuth entity.
type EmployeeAuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployeeAuthMutation
}

// Mutation returns the EmployeeAuthMutation object of the builder.
func (_u *EmployeeAuthUpdateOne) Mutation() *EmployeeAuthMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmployeeAuthUpdate builder.
func (_u *EmployeeAuthUpdateOne) Where(ps ...predicate.EmployeeAuth) *EmployeeAuthUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmployeeAuthUpdateOne) Select(field string, fields ...string) *EmployeeAuthUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmployeeAuth entity.
func (_u *EmployeeAuthUpdateOne) Save(ctx context.Context) (*EmployeeAuth, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeAuthUpdateOne) SaveX(ctx context.Context) *EmployeeAuth {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmployeeAuthUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeAuthUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmployeeAuthUpdateOne) sqlSave(ctx context.Context) (_node *EmployeeAuth, err error) {
	_spec := sqlgraph.NewUpdateSpec(employeeauth.Table, employeeauth.Columns, sqlgraph.NewFieldSpec(employeeauth.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmployeeAuth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employeeauth.FieldID)
		for _, f := range fields {
			if !employeeauth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != employeeauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &EmployeeAuth{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employeeauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
