// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/company"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/department"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/employee"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/predicate"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/queue"
	"github.com/gitwb-c/crm.saas/backend/internal/ent/stage"
	"github.com/google/uuid"
)

// QueueQuery is the builder for querying Queue entities.
type QueueQuery struct {
	config
	ctx                 *QueryContext
	order               []queue.OrderOption
	inters              []Interceptor
	predicates          []predicate.Queue
	withStages          *StageQuery
	withEmployees       *EmployeeQuery
	withDepartment      *DepartmentQuery
	withTenant          *CompanyQuery
	modifiers           []func(*sql.Selector)
	loadTotal           []func(context.Context, []*Queue) error
	withNamedStages     map[string]*StageQuery
	withNamedEmployees  map[string]*EmployeeQuery
	withNamedDepartment map[string]*DepartmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QueueQuery builder.
func (_q *QueueQuery) Where(ps ...predicate.Queue) *QueueQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QueueQuery) Limit(limit int) *QueueQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QueueQuery) Offset(offset int) *QueueQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QueueQuery) Unique(unique bool) *QueueQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QueueQuery) Order(o ...queue.OrderOption) *QueueQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryStages chains the current query on the "stages" edge.
func (_q *QueueQuery) QueryStages() *StageQuery {
	query := (&StageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(queue.Table, queue.FieldID, selector),
			sqlgraph.To(stage.Table, stage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, queue.StagesTable, queue.StagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEmployees chains the current query on the "employees" edge.
func (_q *QueueQuery) QueryEmployees() *EmployeeQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(queue.Table, queue.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, queue.EmployeesTable, queue.EmployeesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDepartment chains the current query on the "department" edge.
func (_q *QueueQuery) QueryDepartment() *DepartmentQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(queue.Table, queue.FieldID, selector),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, queue.DepartmentTable, queue.DepartmentPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *QueueQuery) QueryTenant() *CompanyQuery {
	query := (&CompanyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(queue.Table, queue.FieldID, selector),
			sqlgraph.To(company.Table, company.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, queue.TenantTable, queue.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Queue entity from the query.
// Returns a *NotFoundError when no Queue was found.
func (_q *QueueQuery) First(ctx context.Context) (*Queue, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{queue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QueueQuery) FirstX(ctx context.Context) *Queue {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Queue ID from the query.
// Returns a *NotFoundError when no Queue ID was found.
func (_q *QueueQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{queue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QueueQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Queue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Queue entity is found.
// Returns a *NotFoundError when no Queue entities are found.
func (_q *QueueQuery) Only(ctx context.Context) (*Queue, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{queue.Label}
	default:
		return nil, &NotSingularError{queue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QueueQuery) OnlyX(ctx context.Context) *Queue {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Queue ID in the query.
// Returns a *NotSingularError when more than one Queue ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QueueQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{queue.Label}
	default:
		err = &NotSingularError{queue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QueueQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Queues.
func (_q *QueueQuery) All(ctx context.Context) ([]*Queue, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Queue, *QueueQuery]()
	return withInterceptors[[]*Queue](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QueueQuery) AllX(ctx context.Context) []*Queue {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Queue IDs.
func (_q *QueueQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(queue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QueueQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QueueQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QueueQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QueueQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QueueQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QueueQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QueueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QueueQuery) Clone() *QueueQuery {
	if _q == nil {
		return nil
	}
	return &QueueQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]queue.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.Queue{}, _q.predicates...),
		withStages:     _q.withStages.Clone(),
		withEmployees:  _q.withEmployees.Clone(),
		withDepartment: _q.withDepartment.Clone(),
		withTenant:     _q.withTenant.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithStages tells the query-builder to eager-load the nodes that are connected to
// the "stages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QueueQuery) WithStages(opts ...func(*StageQuery)) *QueueQuery {
	query := (&StageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStages = query
	return _q
}

// WithEmployees tells the query-builder to eager-load the nodes that are connected to
// the "employees" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QueueQuery) WithEmployees(opts ...func(*EmployeeQuery)) *QueueQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmployees = query
	return _q
}

// WithDepartment tells the query-builder to eager-load the nodes that are connected to
// the "department" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QueueQuery) WithDepartment(opts ...func(*DepartmentQuery)) *QueueQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDepartment = query
	return _q
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QueueQuery) WithTenant(opts ...func(*CompanyQuery)) *QueueQuery {
	query := (&CompanyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Queue.Query().
//		GroupBy(queue.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *QueueQuery) GroupBy(field string, fields ...string) *QueueGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QueueGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = queue.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Queue.Query().
//		Select(queue.FieldName).
//		Scan(ctx, &v)
func (_q *QueueQuery) Select(fields ...string) *QueueSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QueueSelect{QueueQuery: _q}
	sbuild.label = queue.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QueueSelect configured with the given aggregations.
func (_q *QueueQuery) Aggregate(fns ...AggregateFunc) *QueueSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QueueQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !queue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QueueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Queue, error) {
	var (
		nodes       = []*Queue{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withStages != nil,
			_q.withEmployees != nil,
			_q.withDepartment != nil,
			_q.withTenant != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Queue).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Queue{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withStages; query != nil {
		if err := _q.loadStages(ctx, query, nodes,
			func(n *Queue) { n.Edges.Stages = []*Stage{} },
			func(n *Queue, e *Stage) { n.Edges.Stages = append(n.Edges.Stages, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEmployees; query != nil {
		if err := _q.loadEmployees(ctx, query, nodes,
			func(n *Queue) { n.Edges.Employees = []*Employee{} },
			func(n *Queue, e *Employee) { n.Edges.Employees = append(n.Edges.Employees, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDepartment; query != nil {
		if err := _q.loadDepartment(ctx, query, nodes,
			func(n *Queue) { n.Edges.Department = []*Department{} },
			func(n *Queue, e *Department) { n.Edges.Department = append(n.Edges.Department, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *Queue, e *Company) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedStages {
		if err := _q.loadStages(ctx, query, nodes,
			func(n *Queue) { n.appendNamedStages(name) },
			func(n *Queue, e *Stage) { n.appendNamedStages(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedEmployees {
		if err := _q.loadEmployees(ctx, query, nodes,
			func(n *Queue) { n.appendNamedEmployees(name) },
			func(n *Queue, e *Employee) { n.appendNamedEmployees(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedDepartment {
		if err := _q.loadDepartment(ctx, query, nodes,
			func(n *Queue) { n.appendNamedDepartment(name) },
			func(n *Queue, e *Department) { n.appendNamedDepartment(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QueueQuery) loadStages(ctx context.Context, query *StageQuery, nodes []*Queue, init func(*Queue), assign func(*Queue, *Stage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Queue)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Stage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(queue.StagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.stage_queue
		if fk == nil {
			return fmt.Errorf(`foreign-key "stage_queue" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "stage_queue" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *QueueQuery) loadEmployees(ctx context.Context, query *EmployeeQuery, nodes []*Queue, init func(*Queue), assign func(*Queue, *Employee)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Queue)
	nids := make(map[uuid.UUID]map[*Queue]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(queue.EmployeesTable)
		s.Join(joinT).On(s.C(employee.FieldID), joinT.C(queue.EmployeesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(queue.EmployeesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(queue.EmployeesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Queue]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Employee](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "employees" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *QueueQuery) loadDepartment(ctx context.Context, query *DepartmentQuery, nodes []*Queue, init func(*Queue), assign func(*Queue, *Department)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Queue)
	nids := make(map[uuid.UUID]map[*Queue]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(queue.DepartmentTable)
		s.Join(joinT).On(s.C(department.FieldID), joinT.C(queue.DepartmentPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(queue.DepartmentPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(queue.DepartmentPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Queue]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Department](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "department" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *QueueQuery) loadTenant(ctx context.Context, query *CompanyQuery, nodes []*Queue, init func(*Queue), assign func(*Queue, *Company)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Queue)
	for i := range nodes {
		fk := nodes[i].TenantId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(company.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenantId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *QueueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QueueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(queue.Table, queue.Columns, sqlgraph.NewFieldSpec(queue.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, queue.FieldID)
		for i := range fields {
			if fields[i] != queue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(queue.FieldTenantId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QueueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(queue.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = queue.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedStages tells the query-builder to eager-load the nodes that are connected to the "stages"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *QueueQuery) WithNamedStages(name string, opts ...func(*StageQuery)) *QueueQuery {
	query := (&StageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedStages == nil {
		_q.withNamedStages = make(map[string]*StageQuery)
	}
	_q.withNamedStages[name] = query
	return _q
}

// WithNamedEmployees tells the query-builder to eager-load the nodes that are connected to the "employees"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *QueueQuery) WithNamedEmployees(name string, opts ...func(*EmployeeQuery)) *QueueQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedEmployees == nil {
		_q.withNamedEmployees = make(map[string]*EmployeeQuery)
	}
	_q.withNamedEmployees[name] = query
	return _q
}

// WithNamedDepartment tells the query-builder to eager-load the nodes that are connected to the "department"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *QueueQuery) WithNamedDepartment(name string, opts ...func(*DepartmentQuery)) *QueueQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedDepartment == nil {
		_q.withNamedDepartment = make(map[string]*DepartmentQuery)
	}
	_q.withNamedDepartment[name] = query
	return _q
}

// QueueGroupBy is the group-by builder for Queue entities.
type QueueGroupBy struct {
	selector
	build *QueueQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QueueGroupBy) Aggregate(fns ...AggregateFunc) *QueueGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QueueGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QueueQuery, *QueueGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QueueGroupBy) sqlScan(ctx context.Context, root *QueueQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QueueSelect is the builder for selecting fields of Queue entities.
type QueueSelect struct {
	*QueueQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QueueSelect) Aggregate(fns ...AggregateFunc) *QueueSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QueueSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QueueQuery, *QueueSelect](ctx, _s.QueueQuery, _s, _s.inters, v)
}

func (_s *QueueSelect) sqlScan(ctx context.Context, root *QueueQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
